services:
  web:
    container_name: demo_web
    build:
      context: ../
      dockerfile: ./demo/web/dockerfile
    volumes:
      - ../:/usr/src/
    ports:
      - '4201:4201'
    command: bash -c "bun install && cd ./demo/web && bun run start:docker"

  api:
    container_name: demo_api
    build:
      context: ../
      dockerfile: ./demo/api/dockerfile
    environment:
      - host=host.docker.internal
    volumes:
      - ../:/usr/src
    ports:
      - '8081:8081'
    expose:
      - 8081
    command: bash -c "bun install && cd ./demo/api && bun run watch"

networks:
  ftoggle_network:
    external:
      name: ftoggle_network
