version: '3.8'

services:
  db:
    image: postgres:16.1
    container_name: ftoggle_db
    volumes:
      - ftoggle_db_data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - '5432:5432'
    expose:
      - 5432

volumes:
  ftoggle_db_data:
    name: ftoggle_db_data
